# Site settings
title: "Minchan Kwon - CV"
description: "Personal CV of Minchan Kwon, Ph.D student at KAIST EE."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Minchan Kwon"
resume_title:                   "About Me"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "kmc020700@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+82-10-8558-1695"
resume_contact_address:         ""

resume_header_contact_info:     "kmc020700@gmail.com &bull; +82-10-8558-1695 &bull; <a href='https://github.com/kmc0207'>github.com/kmc0207</a>"
display_header_contact_info:    "true"

resume_header_intro: "<p>I am a self-motivated PhD student, deeply interested in the intersection of LLMs and RL. To me, reinforcement learning is essential for enabling LLMs to evolve beyond existing knowledge through interaction with the world. In particular, I believe that diversity and swarm intelligence are the keys to LLM RL.</p><p>My research focuses on enhancing the reasoning capability of LLMs through RL. I believe that the current challenges in RL lie in a lack of diversity and getting stuck in failure modes. For this reason, I am very interested in diversity-based methods such as random sampling and genetic algorithms.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          false
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/kmc0207"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
